- name: Cloning roles
  hosts: all
  become: true

  vars:
    git_repository: "https://github.com/Toudi87/Ansible_roles.git"
    git_branch: "master"

  tasks:
  - name: Add folder
    file:
      path: "/etc/ansible/roles/"
      state: directory
      mode: "0755"
  - name: Select branch in repo
    git:
      repo: "{{ git_repository }}"
      dest: "/etc/ansible/roles/"
      version: "{{ git_branch }}"


